# Credit: https://raw.githubusercontent.com/goreleaser/goreleaser/main/.github/ISSUE_TEMPLATE/bug.yaml
name: Bug Report
description: File a bug report
labels: [bug, triage]
assignees:
  - nikoksr
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please fill the form below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: How can we reproduce this?
      description: Please provide a minimal reproducible example
    validations:
      required: true
  - type: textarea
    id: dbench-doctor
    attributes:
      label: dbench doctor
      description: "`dbench doctor` output"
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nikoksr/dbench/blob/trunk/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add
    validations:
      required: false
